# Generated by Django 2.2.3 on 2019-07-28 20:13

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='test',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
