# Generated by Django 2.2.3 on 2019-08-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='LeagueCountry',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='league',
            name='LeagueLogo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='league',
            name='LeagueName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
