# Generated by Django 2.2.3 on 2019-08-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0002_auto_20190814_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='International',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(default='', max_length=100)),
                ('TeamLogo', models.FileField(upload_to='')),
                ('leagues', models.ManyToManyField(to='pick.League')),
            ],
        ),
    ]
