# Generated by Django 2.2.3 on 2019-08-18 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pick', '0004_game_userpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpick',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='AwayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AwayTeam', to='pick.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='HomeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HomeTeam', to='pick.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='League',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pick.League'),
        ),
    ]
