# Generated by Django 2.2.3 on 2019-09-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0005_auto_20190818_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='GameCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='GameResult',
            field=models.CharField(blank=True, choices=[('home', 'home'), ('away', 'away'), ('draw', 'draw')], max_length=10, null=True),
        ),
    ]
